version: 2
approve_by_comment: true
approve_regex: '^(Approved|:\+1:|:lgtm:|lgtm|LGTM)'
reject_regex:  '^(Rejected|:\-1:)'
reset_on_push: false
groups:
  core-committers:
    required: 1
    teams:
      - core
    conditions:
      labels:
        - needs:review-core
  ide-committers:
    required: 1
    teams:
      - ide
    conditions:
      labels:
        - needs:review-lingua
  lingua-committers:
    required: 1
    teams:
      - lingua
    conditions:
      branches:
        - master
  lingua-interns:
    required: 1
    teams:
      - lingua-interns
    conditions:
      labels:
        - needs:review-lingua-interns
